dynamixel_mx28:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: motor_joint
    joint_speed: 2.0
    motor:
        id: 1
        init: 2048
        min: 0
        max: 4095
